Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -15,7 +15,19 @@ jobs:
         uses: actions/checkout@v4
       - name: Unzip Zoopedie project
         run: unzip -q Zoopedie_GitHub_APK_Builder.zip
+      - name: Add Coil
+        run: |
+          GRADLE_FILE=$(find Zoopedie/app -maxdepth 1 \( -name "build.gradle.kts" -o -name "build.gradle" \) | head -n 1)
+          if [ -z "$GRADLE_FILE" ]; then
+            echo "Gradle file not found"
+            exit 1
+          fi
 
+          if [[ "$GRADLE_FILE" == *.kts ]]; then
+            sed -i '/dependencies {/a\    implementation("io.coil-kt:coil-compose:2.7.0")' "$GRADLE_FILE"
+          else
+            sed -i "/dependencies {/a\\    implementation 'io.coil-kt:coil-compose:2.7.0'" "$GRADLE_FILE"
+          fi
       - name: Update MainActivity
         run: |
               MAIN_ACTIVITY=$(find Zoopedie/app/src/main -name MainActivity.kt | head -n 1)
